/* Technology archive only: accessible inline expansion. */
(function () {
  'use strict';
  var archive = document.querySelector('[data-technology-archive]');
  if (!archive) return;
  function beginAnimation(el) { if (el._animationTransitionHandler) { el.removeEventListener('transitionend', el._animationTransitionHandler); el._animationTransitionHandler = null; } if (el._animationFallbackTimer) { window.clearTimeout(el._animationFallbackTimer); el._animationFallbackTimer = null; } el._animationToken = (el._animationToken || 0) + 1; return el._animationToken; }
  function animateExpand(el, reducedMotion) { var token = beginAnimation(el); el.hidden = false; if (reducedMotion) { el.style.maxHeight = 'none'; el.classList.add('is-expanded'); return; } el.style.maxHeight = '0px'; el.offsetHeight; var target = el.scrollHeight; el.style.maxHeight = target + 'px'; el.classList.add('is-expanded'); var onEnd = function (e) { if (token !== el._animationToken || e.target !== el || e.propertyName !== 'max-height') return; el.style.maxHeight = 'none'; el._animationTransitionHandler = null; el.removeEventListener('transitionend', onEnd); }; el._animationTransitionHandler = onEnd; el.addEventListener('transitionend', onEnd); }
  function animateCollapse(el, reducedMotion) { var token = beginAnimation(el); if (reducedMotion) { el.style.maxHeight = ''; el.classList.remove('is-expanded'); el.hidden = true; return; } var current = el.scrollHeight; el.style.maxHeight = current + 'px'; el.offsetHeight; el.classList.remove('is-expanded'); el.style.maxHeight = '0px'; var onEnd = function (e) { if (token !== el._animationToken || e.target !== el || e.propertyName !== 'max-height') return; el.hidden = true; el.style.maxHeight = ''; el._animationTransitionHandler = null; el.removeEventListener('transitionend', onEnd); if (el._animationFallbackTimer) { window.clearTimeout(el._animationFallbackTimer); el._animationFallbackTimer = null; } }; el._animationTransitionHandler = onEnd; el.addEventListener('transitionend', onEnd); el._animationFallbackTimer = window.setTimeout(function () { if (token !== el._animationToken || el.hidden) return; el.hidden = true; el.style.maxHeight = ''; if (el._animationTransitionHandler === onEnd) { el._animationTransitionHandler = null; el.removeEventListener('transitionend', onEnd); } el._animationFallbackTimer = null; }, 400); }
  var cards = Array.prototype.slice.call(document.querySelectorAll('.technology-card')); cards.forEach(function (card) { var trigger = card.querySelector('.technology-card__trigger'); if (!trigger) return; card.setAttribute('data-technology-card', ''); trigger.addEventListener('click', function () { setOpen(card, trigger.getAttribute('aria-expanded') !== 'true', false); }); card.addEventListener('keydown', function (event) { if (event.key === 'Escape' && trigger.getAttribute('aria-expanded') === 'true') { event.preventDefault(); setOpen(card, false, true); } }); });
  function flipCardPosition(card, mutate) { var reducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches; if (reducedMotion) { mutate(); return; } if (card._flipTransitionHandler) { card.removeEventListener('transitionend', card._flipTransitionHandler); card._flipTransitionHandler = null; } if (card._flipFrame) { window.cancelAnimationFrame(card._flipFrame); card._flipFrame = null; } card._flipToken = (card._flipToken || 0) + 1; var token = card._flipToken; var first = card.getBoundingClientRect(); mutate(); var last = card.getBoundingClientRect(); var dx = first.left - last.left; var dy = first.top - last.top; if (!dx && !dy) return; card.style.transition = 'none'; card.style.transform = 'translate(' + dx + 'px, ' + dy + 'px)'; card.offsetHeight; card._flipFrame = requestAnimationFrame(function () { card._flipFrame = null; if (token !== card._flipToken) return; card.style.transition = 'transform var(--dur-trans) var(--ease-out-soft)'; card.style.transform = ''; var onEnd = function (e) { if (token !== card._flipToken || e.target !== card || e.propertyName !== 'transform') return; card.style.transition = ''; card._flipTransitionHandler = null; card.removeEventListener('transitionend', onEnd); }; card._flipTransitionHandler = onEnd; card.addEventListener('transitionend', onEnd); }); }
  function setOpen(card, open, restoreFocus) { var trigger = card.querySelector('.technology-card__trigger'); var body = card.querySelector('.technology-card__body'); if (!trigger || !body) return; flipCardPosition(card, function () { card.setAttribute('data-open', open ? 'true' : 'false'); }); trigger.setAttribute('aria-expanded', open ? 'true' : 'false'); var reducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches; var scrollBehavior = reducedMotion ? 'auto' : 'smooth'; if (open) { animateExpand(body, reducedMotion); if (restoreFocus) body.scrollIntoView({ block: 'nearest', behavior: scrollBehavior }); } else { animateCollapse(body, reducedMotion); if (restoreFocus) trigger.focus(); } }
})();
(function () {
  'use strict';
  var table = document.querySelector('.anime-catalogue__table');
  if (!table) return;
  var tbody = table.querySelector('tbody');
  var rows = Array.prototype.slice.call(tbody.querySelectorAll('tr'));
  var sortButtons = Array.prototype.slice.call(document.querySelectorAll('.anime-catalogue__sort-btn'));
  var currentSort = 'no';
  var currentDirection = 'ascending';
  var rowData = rows.map(function (row, index) { return { element: row, chronology: parseInt(row.getAttribute('data-chronology'), 10) || 0, type: row.getAttribute('data-type') || '', language: row.getAttribute('data-language') || '', name: row.querySelector('.anime-catalogue__name') ? row.querySelector('.anime-catalogue__name').textContent.trim() : '', originalIndex: index }; });
  function sortRows(sortKey, direction) { var sorted = rowData.slice().sort(function (a, b) { var valA, valB; switch (sortKey) { case 'no': valA = a.chronology; valB = b.chronology; break; case 'name': valA = a.name.toLowerCase(); valB = b.name.toLowerCase(); break; case 'type': valA = a.type; valB = b.type; break; case 'language': valA = a.language; valB = b.language; break; default: valA = a.chronology; valB = b.chronology; } var cmp = 0; if (valA < valB) cmp = -1; else if (valA > valB) cmp = 1; if (cmp === 0 && sortKey !== 'no') cmp = a.chronology - b.chronology; if (cmp === 0) cmp = a.originalIndex - b.originalIndex; return direction === 'ascending' ? cmp : -cmp; }); sorted.forEach(function (item) { tbody.appendChild(item.element); }); }
  function updateButtonStates(activeButton, direction) { sortButtons.forEach(function (btn) { var isActive = btn === activeButton; btn.setAttribute('aria-pressed', isActive ? 'true' : 'false'); btn.removeAttribute('aria-sort'); if (isActive) btn.setAttribute('aria-sort', direction); }); }
  sortButtons.forEach(function (btn) { btn.addEventListener('click', function () { var sortKey = btn.getAttribute('data-sort'); var direction = 'ascending'; if (sortKey === currentSort) direction = currentDirection === 'ascending' ? 'descending' : 'ascending'; currentSort = sortKey; currentDirection = direction; sortRows(sortKey, direction); updateButtonStates(btn, direction); }); btn.addEventListener('keydown', function (event) { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); btn.click(); } }); });
  sortRows('no', 'ascending');
})();